### ISSUE TITLE
train_distributed.py - line 526

### ISSUE THREAD

**Issue by talrub** [Ping-C/optimizer#6]
Hi,
At line 526 you wrote: perfect_model_weights.append(model_result.get_weights_by_idx(perfect_model_idxs)) .

Shouldn't it be: perfect_model_weights.append(model_result.get_weights_by_idx(perfect_model_idxs.nonzero().squeeze(1))) ,
(similar to line 524) in order to take only models that correspond to the condition: ((es_l< train_loss) & (train_loss <= es_u) & (train_acc == 1.0)) instead of taking all models.

Thanks

**Comment by Ping-C** [comment]
Sorry. I have been busy, so did not respond quickly. I believe that pytorch support boolean indexing which selects only index with True and exclude entries with False, so this should work as expected without .nonzero().
